### ISSUE TITLE
爱奇艺解析bug

### ISSUE THREAD

**Issue by 1422384664** [hecoter/videoParse#2]
明明有node_vm2\vm-server'
却报错

Error: Cannot find module 'C:\Users\destiny\AppData\Local\Temp\_MEI59402\node_vm2\vm-server'
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)[39m
[90m    at node:internal/main/run_main_module:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by hecoter** [comment]
用python运行源码，不要打包成成品运行。NodeVM 本身bug，换成execjs就行了
